<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-N8E3DN4O" failures="1" tests="15" name="Surefire test" time="0.134" errors="0" timestamp="2025-05-03T20:45:35 WIB">
  <testcase classname="com.swt.OperationTest" name="add_TC1_posInt" time="0.011"/>
  <testcase classname="com.swt.OperationTest" name="add_TC2_negInt" time="0.001"/>
  <testcase classname="com.swt.OperationTest" name="add_TC3_mixInt" time="0.001"/>
  <testcase classname="com.swt.OperationTest" name="add_TC4_mixDec" time="0.0"/>
  <testcase classname="com.swt.OperationTest" name="add_TC5_zero" time="0.001"/>
  <testcase classname="com.swt.OperationTest" name="mul_TC1_posInt" time="0.0"/>
  <testcase classname="com.swt.OperationTest" name="mul_TC2_negInt" time="0.0"/>
  <testcase classname="com.swt.OperationTest" name="mul_TC3_mixInt" time="0.001"/>
  <testcase classname="com.swt.OperationTest" name="mul_TC4_mixDec" time="0.001"/>
  <testcase classname="com.swt.OperationTest" name="mul_TC5_zero" time="0.0"/>
  <testcase classname="com.swt.ValidatorTest" name="checkRange_TC1" time="0.001"/>
  <testcase classname="com.swt.ValidatorTest" name="checkRange_TC2" time="0.001"/>
  <testcase classname="com.swt.ValidatorTest" name="checkRange_TC3" time="0.0"/>
  <testcase classname="com.swt.ValidatorTest" name="checkRange_TC4" time="0.0"/>
  <testcase classname="com.swt.ValidatorTest" name="checkRange_TC5" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [NONE] but found [OUT_OF_RANGE]">
      <![CDATA[java.lang.AssertionError: expected [NONE] but found [OUT_OF_RANGE]
at com.swt.ValidatorTest.checkRange_TC5(ValidatorTest.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- checkRange_TC5 -->
</testsuite> <!-- Surefire test -->
